Aron Widforss:
  email:
    address: aron@antarkt.is
John Doe:
  email:
    address: johndoe@email.com
Niklas:
  email:
    address: niklas@email.com
John Wilsson:
  email:
    address: john.wilsson@email.com
John Andersson:
  email:
    address: jAndersson@email.com
Hugo Wangler:
  email:
    address: hugo@email.com
