english:
  - version: "0.0.1"
    modules:
      - module: spacy
        name: en_core_web_md
        command:
          - -m
          - spacy
          - download
          - en_core_web_sm
      - module: basic
        name: en_rpa_simple
        tar: 'https://github.com/rpa-tomorrow/model-releases/releases/download/en_rpa_simple-0.0.1/en_rpa_simple-0.0.1.tar.gz'
      - module: reminder
        name: en_rpa_simple_reminder
        tar: 'https://github.com/rpa-tomorrow/model-releases/releases/download/en_rpa_simple_reminder-0.0.1/en_rpa_simple_reminder-0.0.1.tar.gz'
      - module: schedule
        name: en_rpa_simple_calendar
        tar: 'https://github.com/rpa-tomorrow/model-releases/releases/download/en_rpa_simple_calendar-0.0.3/en_rpa_simple_calendar-0.0.3.tar.gz'
      - module: email
        name: en_rpa_simple_email
        tar: 'https://github.com/rpa-tomorrow/model-releases/releases/download/en_rpa_simple_email-0.0.1/en_rpa_simple_email-0.0.1.tar.gz'
